version: '3.8'
services:
  app:
    image: atemndobs/nutriscan-amd64:v0.0.2
    platform: linux/amd64
    container_name: nutri-scanorama
    ports:
      #  - "2025:5173"  # Vite dev server
      - "3002:3002"  # Proxy server
      - "2025:8080"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_API_KEY_GLHF=${VITE_API_KEY_GLHF:-your_api_key_here}
      - VITE_API_URL_GLHF=https://glhf.chat/api/openai/v1
      - VITE_BASE_URL_GLHF=https://nutriscan.atemkeng.de/api/glhf
      - VITE_AI_FAST_MODEL_GLHF="hf:meta-llama/Llama-3.2-1B-Instruct"
      - VITE_AI_PRECISE_MODEL_GLHF="hf:Qwen/Qwen2.5-Coder-32B-Instruct"
      - VITE_API_URL_LMSTUDIO=https://mac.goose-neon.ts.net/v1
      - VITE_BASE_URL_LMSTUDIO=https://nutriscan.atemkeng.de/api/lmstudio
      - VITE_AI_FAST_MODEL_LMSTUDIO="unsloth/llama-3.2-1b-instruct"
      - VITE_AI_PRECISE_MODEL_LMSTUDIO="qwen2.5-coder-23b-instruct"
    volumes:
      - .:/app  # Mount root directory
      - ./public:/app/public  # Mount public directory
    restart: unless-stopped